runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /vendor
  static_dir: www/vendor

- url: /css
  static_dir: www/css

- url: /.*
  script: miniproject.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest